import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./components/navbar/Navbar"
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import ProductosLista from "./pages/productos/listaProductos/ListaProductos";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "administracion de clientes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Navbar/>
        <Footer/>
        <ProductosLista />
      </body>
    </html>
  );
}